name: Package on Release

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup environment
        run: |
          mkdir AutoSuggestAI

      - name: Copy files excluding .git and hidden files
        run: |
          shopt -s extglob dotglob
          cp -r !(AutoSuggestAI|.git) AutoSuggestAI/

      - name: Package plugin
        run: |
          zip -r AutoSuggestAI.zip AutoSuggestAI -x "*.git*"

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: AutoSuggestAI.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}